### ISSUE TITLE
packer.lua 中没有clean方法，导致lua require('aloha.prepare')执行失败

### ISSUE THREAD

**Issue by xuyaojianfei** [alohaia/nvimcfg#2]
E5108: Error executing lua /home/chen/.config/nvim/lua/aloha/prepare.lua:13: attempt to call method 'clean' (a nil value)

**Comment by alohaia** [comment]
已在 649d297c635c4df5e8569d3c74c3aa2451956121 修复，感谢反馈 @xuyaojianfei。
